#!/bin/sh

PORT=8082
HOST=cid

command=$1

if [ "$command" == "" ]; then
  echo "Syntax: sdv <name> [value=true]"
  exit
fi

value=$2
if [ "$value" == "" ]; then
  value="true"
fi

BASEDIR=$(dirname "$0")

socat tcp:$HOST:$PORT EXEC:"bash $BASEDIR/send.sh '{\"method\":\"set_data_value\",\"params\":[{\"name\":\"$command\",\"value\":\"$value\"}]}' 'set_data_value'"